## 01. 미분


미분의 기본 개념은 함수의 변화율을 구하는 데 있다. 이는 함수가 입력의 변화에 따라 얼마나 변하는지를 수학적으로 분석하는 도구이다.


### 01-01. 평균 변화율


먼저, 함수 $f(x)$의 **평균 변화율**을 살펴본다. 이는 두 점 $x$와 $x + h$ 사이에서 함수 $f(x)$가 얼마나 변했는지를 나타내는 지표이다.


$$
평균변화율 = \frac{f(x + h) − f(x)}{h}
$$


예를 들어, $f(x) = 2x$라 할 때, $x=5$에서 $x=8$로 바뀌었다고 하면, 평균 변화율은 다음과 같다.


$$
\frac{f(8) - f(5)}{3} = \frac{16 - 10}{3} = 2
$$


이는 $h$만큼의 변화에 대해 함수 $f$가 얼마나 변하는지를 나타내며, 기울기의 개념과도 연결된다.


### 01-02. 순간 변화율 (미분의 정의)


**순간 변화율**은 평균 변화율에서 $h$가 0에 극한으로 가까워질 때를 의미한다. 이를 통해 미분을 정의할 수 있다.


$$
f′(x) = \lim_{h→0}\frac{f(x + h) − f(x)}{h}
$$


**예: $f(x) = x^2$의 미분**


$$
\frac{(x + h)^2 − x^2}{h} = \frac{x^2 + 2xh + h^2 − x^2}{h} = \frac{2xh + h^2}{h} = 2x + h
$$


극한을 취하면 다음과 같다.


$$
\lim_{h → 0}(2x + h) = 2x
$$


따라서, $f(x) = x^2$의 미분은 $f′(x) = 2x$이다.


### 01-03. 다양한 미분 예시


#### 01-03-01. 다항 함수 $f(x) = x^2$


위와 같이 전개 및 극한을 통해 다음을 얻는다.


$$
f′(x) = 2x
$$


#### 01-03-02. 상수 함수 $f(x) = c$


$$
\frac{f(x + h) − f(x)}{h} = \frac{c − c}{h} = 0
$$


상수 함수는 입력 변화에 관계없이 값이 일정하므로 미분값은 항상 0이다.


$$
f′(x) = 0
$$


#### 01-03-03. 선형 함수 $f(x) = mx + b$


$$
\frac{f(x + h) − f(x)}{h} = \frac{m(x + h) + b − (mx + b)}{h} = \frac{mh}{h} = m
$$


따라서, 선형 함수의 미분은 $f′(x) = m$이다.


### 01-04. 미분의 기본 규칙


1. 상수 $c$의 미분은 $0$이다.
2. $f(x) = x^n$ 형태의 미분은 $nx^{n−1}$이다.
3. 함수의 선형 조합 $af(x) + bg(x)$의 미분은 $af′(x) + bg′(x)$이다.


### 01-05. 미분 표기


라이프니츠는 미분을 다음과 같은 표기로 정의하였다:


* $d$: differential, 미소한 변화
* $dx$: $x$의 미소 변화
* $\frac{d}{dx}$: $x$에 대한 미분 연산자


**연쇄 법칙 표기**


합성 함수 $z = f(g(x))$에 대해 다음과 같이 연쇄법칙을 적용할 수 있다:


$$
\frac{dz}{dx} = \frac{dz}{dy} \cdot \frac{dy}{dx}
$$


### 01-06. 미분의 연쇄 법칙


합성 함수 $y = f(g(x))$의 미분은 내부 함수와 외부 함수의 미분을 곱하여 구한다.


* $y = f(u)$
* $u = g(x)$


이때:


$$
\frac{dy}{dx} = \frac{dy}{du} \cdot \frac{du}{dx}
$$


**예시**


$z = y^2$, $y = 5x + 2$인 경우,


$$
\frac{dz}{dx} = \frac{dz}{dy} \cdot \frac{dy}{dx} = 2y \cdot 5 = 10y
$$


$y = 5x + 2$이므로:


$$
\frac{dz}{dx} = 10(5x + 2) = 50x + 20
$$


이는 직접 미분한 결과와 동일하다.


## 02. 미분과 수치미분 개념


**수학적 미분 (Analytical Differentiation)**


$$
f(x) = x^2 \Rightarrow f'(x) = 2x
$$


* 수학적으로 정확한 **도함수**를 구함
* 함수의 변화율을 계산하는 공식 기반 미분


**수치미분 (Numerical Differentiation)**
$$
f'(x) \approx \frac{f(x+h) - f(x-h)}{2h}
$$
* 도함수를 직접 구하지 않고, **근사값으로 기울기를 계산**
* 여기서 $h$는 아주 작은 수 (예: $h = 1e-4$)
* 실제 계산 과정을 코드로 볼 수 있어 **직관적**


**미분 vs 수치미분 비교표**


| 항목    | 수학적 미분 (Analytical) | 수치미분 (Numerical)          |
| ----- | ------------------- | ------------------------- |
| 정의 방식 | 공식에 따라 도함수 계산       | 근사값으로 기울기 계산              |
| 정확도   | 매우 정확함              | 근사값, 오차 발생 가능             |
| 속도    | 빠름                  | 느림 (함수값 여러 번 계산 필요)       |
| 용도    | 모델 학습, 역전파 계산       | 디버깅, 검증용 (Gradient Check) |


**수치미분 방식비교**


> 중앙차분(Central Difference) 방식이 가장 보편적으로 사용된다.


| 방식   | 수식                                           | 정확도    | 계산 비용 | 특징         |
| ---- | -------------------------------------------- | ------ | ----- | ---------- |
| 전진차분 | $f'(x) \approx \frac{f(x+h) - f(x)}{h}$    | 1차 정확도 | 낮음    | 간단하지만 오차 큼 |
| 후진차분 | $f'(x) \approx \frac{f(x) - f(x-h)}{h}$    | 1차 정확도 | 낮음    | 전진과 비슷     |
| 중앙차분 | $f'(x) \approx \frac{f(x+h) - f(x-h)}{2h}$ | 2차 정확도 | 높음    | 정확하고 균형잡힘  |


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

In [3]:
def f(x) :
    return x ** 2

# 수학적 미분
def df(x) :
    return 2 * x

# 수치미분(중앙차분)
def nummerical_diff(x, h=1e-4) :
    return (f(x + h) - f(x - h)) / (2 * h)

# 전진차분
def nummerical_diff_forward(x, h=1e-4) :
    return (f(x + h) - f(x)) / h

# 후진차분
def nummerical_diff_backward(x, h=1e-4) :
    return (f(x) - f(x - h)) / h

x = np.array(4)
print(f(x))
print(df(x)) # x에 따른 f(x) 순간 기울기 (미분한 값)
print(nummerical_diff(x))
print(nummerical_diff_forward(x))
print(nummerical_diff_backward(x))

16
8
7.999999999999119
8.00009999998963
7.9999000000086085


## 03. pyTorch의 자동미분

In [4]:
# 연산을 시작하는 텐서
x = torch.tensor(4. , requires_grad=True)
# y = f(x) # x ** 2
y = x ** 2

print(y)
print(y.grad_fn) # tensor 연산기록 객체, 직접 실행 불가. 나 무슨무슨 계산 했어요~
y.backward() # 미분(기울기) 계산이 거꾸로 처리, 계산 결과는 x.grad 속성에 저장

print(x.grad)


tensor(16., grad_fn=<PowBackward0>)
tensor(8.)


In [5]:
# 복잡한 연산
x = torch.tensor([4.0], requires_grad=True) # 리프텐서(연관그래프 시작점) 미분대상
y = (x * 3 + 5) ** 2
print(y)

print(y.grad_fn)
print(y.grad_fn.next_functions)

# 연산그래프 추적 함수
def print_grad_fn_tree(fn, indent=0) :
    # 재귀함수 종료 조건
    if fn is None :
        return

    print(' ' * indent + f'└{fn.__class__.__name__}')

    if hasattr(fn, 'next_functions') :
        for sub, _ in fn.next_functions :
            print_grad_fn_tree(sub, indent + 4)

print_grad_fn_tree(y.grad_fn ) # y = (x * 3 + 5) ** 2

y.backward()
print(x.grad)

tensor([289.], grad_fn=<PowBackward0>)
((<AddBackward0 object at 0x0000018782B65AB0>, 0),)
└PowBackward0
    └AddBackward0
        └MulBackward0
            └AccumulateGrad
tensor([102.])


## 04. 다변수함수 미분(편미분)

In [6]:
# 다변수 미분
def f(x, y) :
    return x ** 2 + y ** 2

# (도함수) f에 대한 x편미분  # 빵
def df_dx(x, y) :
    return 2 * x
# (도함수) f에 대한 y편미분 # 딸기라떼
def df_dy(x, y) :
    return 2 * y

# 수치미분 # 도함수를 이용한 게 아니라 근사값 갖고 하는 것
def numerical_partial_diff(f, x, y, var='x', h=1e-4) :
    if var == 'x' :
        return (f(x + h, y) - f(x - h, y)) / (2 * h)
    else :
        return (f(x, y + h) - f(x, y - h)) / (2 * h)


print(f(3, 4))
print('df_dx : ', df_dx(3, 4))
print('df_dy : ', df_dy(3, 4))

print('x에 대한 수치편미분 : ', numerical_partial_diff(f, 3, 4, var='x'))
print('y에 대한 수치편미분 : ', numerical_partial_diff(f, 3, 4, var='y'))

25
df_dx :  6
df_dy :  8
x에 대한 수치편미분 :  6.00000000000378
y에 대한 수치편미분 :  7.999999999999119


In [7]:
# torch 자동미분
x = torch.tensor(3., requires_grad=True)
y = torch.tensor(4., requires_grad=True)

z = f(x, y) # x ** 2 + y ** 2
print(z) # tensor(25., grad_fn=<AddBackward0>)
print_grad_fn_tree(z.grad_fn)

z.backward() # 옵션 틀어놓고 백워드만 하면 결과값 동일하게 얻을 수 있고 연산 그래프 추적도 가능하다.
print(x.grad.item())
print(y.grad.item())

tensor(25., grad_fn=<AddBackward0>)
└AddBackward0
    └PowBackward0
        └AccumulateGrad
    └PowBackward0
        └AccumulateGrad
6.0
8.0


# 선형층

* 입력: $x$ (고정)
* 실제 정답: $y$ (고정)
* 예측: $\hat{y} = wx + b$
* 손실: $L = (\hat{y} - y)^2 = (wx + b - y)^2$




즉, 손실 함수를


$$
L(w, b) = (wx + b - y)^2
$$


로 보고, $w$와 $b$에 대해 편미분한다.


**수학적 미분**


$$
\frac{\partial L}{\partial w} = 2(wx + b - y) \cdot x \\
$$
$$
\frac{\partial L}{\partial b} = 2(wx + b - y)
$$

In [8]:
# 선형층 + 손실 함수 구현
def L(w, x, b, y) :
    y_hat = w * x + b
    loss = (y_hat - y) ** 2
    return loss

def dl_dw(w, x, b, y) :
    return 2 * (w * x + b - y) * x

def dl_db(w, x, b, y) :
    return 2 * (w * x + b - y)

# x, y : 지도학습에 제공된 값(고정)
# w, b : 모델이 학습할 가중치/절편 (미분대상)
w, x, b, y = 2.0, 3.0, 1.0, 10.0

print(L(w, x, b, y))
print('L을 w로 편미분 : ', dl_dw(w, x, b, y))
print('L을 b로 편미분 : ', dl_db(w, x, b, y))

9.0
L을 w로 편미분 :  -18.0
L을 b로 편미분 :  -6.0


In [9]:
# torch
x = torch.tensor(3.0)
y = torch.tensor(10.0)
w = torch.tensor(2.0, requires_grad=True) # 미분을 하려면 이 요소가 꼭 필요해용
b = torch.tensor(1.0, requires_grad=True) # 기존에는 이 코드를 작성한적이 없는데, 기본적으로는 내부적으로 다 돌아갑니당 실습해보기 위해 직접 작성하는거에욥

loss = L(w, x, b, y)
print(loss)

loss.backward()
print('L을 w로 편미분 : ', w.grad.item())
print('L를 b로 편미분 : ', b.grad.item())
print(x.grad)
print(y.grad)

tensor(9., grad_fn=<PowBackward0>)
L을 w로 편미분 :  -18.0
L를 b로 편미분 :  -6.0
None
None


## 06.벡터/행렬 형태


* 예측 함수: $\hat{y} = \mathbf{w}^\top \mathbf{x} + b$
* 손실 함수: $L = (\hat{y} - y)^2$
* 가중치 벡터 $\mathbf{w}$에 대한 편미분
* NumPy 및 PyTorch 코드 비교


**목표**


$$
\hat{y} = \mathbf{w}^\top \mathbf{x} + b \\
L = (\hat{y} - y)^2 = (\mathbf{w}^\top \mathbf{x} + b - y)^2
$$


* $\mathbf{x}$: 입력 벡터 (예: 특징 3개짜리 입력)
* $\mathbf{w}$: 가중치 벡터
* $b$: 편향
* $y$: 정답 (스칼라)


**수학적으로 편미분**


손실 함수:


$$
L(\mathbf{w}, b) = (\mathbf{w}^\top \mathbf{x} + b - y)^2
$$


1. $\frac{\partial L}{\partial \mathbf{w}}$


$$
\frac{\partial L}{\partial \mathbf{w}} = 2(\mathbf{w}^\top \mathbf{x} + b - y) \cdot \mathbf{x}
$$


2. $\frac{\partial L}{\partial b}$


$$
\frac{\partial L}{\partial b} = 2(\mathbf{w}^\top \mathbf{x} + b - y)
$$


In [10]:
# 벡터/행렬형태의 선형층 + 손실함수
X = np.array([[1., 2., 3.], [4., 5., 6.]]) # (2, 3)
y = np.array([2.])
W = np.array([[0.1, 0.2, 0.3]]) # (1, 3)
b = np.array([0.5])

def L(W, X, b, y) :
    y_hat = X @ W.T + b
    loss = (y_hat - y) ** 2
    return np.mean(loss)

def dl_dW(W, X, b, y) :
    y_hat = X @ W.T + b
    return np.mean(2 * (y_hat - y) * X, axis=0)

def dl_db(W, X, b, y) :
    y_hat = X @ W.T + b
    return np.mean(2 * (y_hat - y), axis=0)

print(L(W, X, b, y))
print('L에 대한 W편미분 : ', dl_dW(W, X, b, y))
print('L에 대한 b편미분 : ', dl_db(W, X, b, y))

1.4499999999999997
L에 대한 W편미분 :  [6.7 8.3 9.9]
L에 대한 b편미분 :  [1.6]


In [11]:
# 자동미분
X = torch.tensor([[1., 2., 3.], [4., 5., 6.]]) # (2, 3)
y = torch.tensor([2.])
W = torch.tensor([[0.1, 0.2, 0.3]], requires_grad=True) # (1, 3)
b = torch.tensor([0.5], requires_grad=True)

def L(W, X, b, y) :
    y_hat = X @ W.T + b
    loss = (y_hat - y) ** 2
    return torch.mean(loss)

loss = L(W, X, b, y)
print(loss)

loss.backward() # ***** 이거 하면 알아서 W에 대한 기울기, b에 대한 기울기
print(W.grad)
print(b.grad)



tensor(1.4500, grad_fn=<MeanBackward0>)
tensor([[6.7000, 8.3000, 9.9000]])
tensor([1.6000])


## 07.Gradient Descent 가중치 업데이트 방식 비교


| 방식                | 설명                | 특징           |
| ----------------- | ----------------- | ------------ |
| **Batch GD**      | 전체 데이터로 한 번에 업데이트 | 가장 안정적, 느림   |
| **Mini-Batch GD** | 일부 데이터(배치)마다 업데이트 | 일반적인 학습 방식   |
| **SGD**           | 한 데이터마다 바로 업데이트   | 노이즈 큼, 빠른 반응 |




**공통 조건**


* 문제: 단순 선형 회귀 $y = wx + b$
* 손실: MSE (평균제곱오차)
* 데이터: 임의의 간단한 샘플로 구성 (2차원 입력, 100개 샘플)

### tensor 직접 제어

- BGD
- Mini-batch GD
- SGD

In [12]:
# 데이터 생성
torch.manual_seed(42)

X = torch.randn(100, 2)
W_true = torch.tensor([[2.0, -3.0]])
b_true = torch.tensor([5.0])
y = X @ W_true.T + b_true + torch.randn(100, 1) * 0.5


print(X.shape, y.shape)

torch.Size([100, 2]) torch.Size([100, 1])


In [13]:
# 1. BGD
W = torch.zeros(1, 2, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

lr = 0.1

for epoch in range(20):
    y_hat = X @ W.T + b
    loss = torch.mean((y_hat - y) ** 2) # 스칼라
    loss.backward()

    # 최적화함수 대신 직접 갱신
    with torch.no_grad() :
        W -= lr * W.grad
        b -= lr * b.grad

        W.grad.zero_() # 메소드_형식일때는 in-place 처리 W.grad = W.grad.zero()
                    # 원래는 직접 주입 시켜줘야 하는데, 좀 간단하게 쓸 수 있는 방법이다!
        b.grad.zero_()

    print(f'epoch: {epoch + 1}, loss: {loss.item():4f}')

epoch: 1, loss: 26.907991
epoch: 2, loss: 19.797335
epoch: 3, loss: 14.713387
epoch: 4, loss: 11.029496
epoch: 5, loss: 8.329667
epoch: 6, loss: 6.332347
epoch: 7, loss: 4.843369
epoch: 8, loss: 3.726490
epoch: 9, loss: 2.884600
epoch: 10, loss: 2.247530
epoch: 11, loss: 1.763981
epoch: 12, loss: 1.396084
epoch: 13, loss: 1.115659
epoch: 14, loss: 0.901599
epoch: 15, loss: 0.738015
epoch: 16, loss: 0.612897
epoch: 17, loss: 0.517133
epoch: 18, loss: 0.443799
epoch: 19, loss: 0.387618
epoch: 20, loss: 0.344564


In [14]:
# 2. Mini-batch 방식
W = torch.zeros(1, 2, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

lr = 0.1
batch_size = 20 # 100개의 샘플을 20개씩 5번 처리 (하나의 epoch당)

for epoch in range(20):
    indices = torch.randperm(X.size(0)) # X.size(0) == 100
    #print(indices.numpy())

    for i in range(0, X.size(0), batch_size): # 가중치랑 절편 알기 위해서
        batch_index = indices[i: i + batch_size]
        # print('           ', batch_index.numpy())
        X_batch = X[batch_index]
        y_batch = y[batch_index]

        y_hat = X_batch @ W.T + b
        loss = torch.mean((y_hat - y_batch) ** 2)

        loss.backward()

        with torch.no_grad():
            # 기울기 갱신
            W -= lr * W.grad
            b -= lr * b.grad

            # 기울기 초기화
            W.grad.zero_()
            b.grad.zero_()

    print(f'epoch {epoch + 1} : loss {loss.item():4f}')


epoch 1 : loss 6.813109
epoch 2 : loss 2.998341
epoch 3 : loss 0.779806
epoch 4 : loss 0.375116
epoch 5 : loss 0.281189
epoch 6 : loss 0.186157
epoch 7 : loss 0.194360
epoch 8 : loss 0.142639
epoch 9 : loss 0.197583
epoch 10 : loss 0.214594
epoch 11 : loss 0.176423
epoch 12 : loss 0.214267
epoch 13 : loss 0.253670
epoch 14 : loss 0.328991
epoch 15 : loss 0.189103
epoch 16 : loss 0.178879
epoch 17 : loss 0.259712
epoch 18 : loss 0.272574
epoch 19 : loss 0.229838
epoch 20 : loss 0.213572


In [15]:
# 3. SGD 확률적 경사하강법
# batch_size = 1인 미니배치 경사하강법
W = torch.zeros(1, 2, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

lr = 0.1

for epoch in range(20):
    indices = torch.randperm(X.size(0)) # 데이터 샘플 수

    for i in indices:
        X_i = X[i]
        y_i = y[i]

        y_hat = X_i @ W.T + b
        loss = torch.mean((y_hat - y_i) ** 2)

        loss.backward()

        with torch.no_grad():
            # 기울기 갱신
            W -= lr * W.grad
            b -= lr * b.grad

            # 기울기 초기화
            W.grad.zero_()
            b.grad.zero_()

    print(f'epoch {epoch + 1} : loss {loss.item():4f}')


epoch 1 : loss 0.000100
epoch 2 : loss 0.813070
epoch 3 : loss 0.509737
epoch 4 : loss 0.081824
epoch 5 : loss 0.200389
epoch 6 : loss 0.244128
epoch 7 : loss 0.309414
epoch 8 : loss 0.331610
epoch 9 : loss 0.003295
epoch 10 : loss 0.322557
epoch 11 : loss 0.175953
epoch 12 : loss 0.106600
epoch 13 : loss 1.069683
epoch 14 : loss 1.058720
epoch 15 : loss 0.007500
epoch 16 : loss 0.207045
epoch 17 : loss 0.164256
epoch 18 : loss 0.109542
epoch 19 : loss 0.004170
epoch 20 : loss 0.060047


# DataSet / DataLoader
- BGD
- Mini-batch GD
- SGD

In [18]:
# 데이터 생성
X = torch.linspace(0, 10, 100).unsqueeze(1) # 0부터 10까지 균등한 값 100개 뽑아줘
y = 3 * X + 1 + torch.randn_like(X) * 0.5
print(X)

tensor([[ 0.0000],
        [ 0.1010],
        [ 0.2020],
        [ 0.3030],
        [ 0.4040],
        [ 0.5051],
        [ 0.6061],
        [ 0.7071],
        [ 0.8081],
        [ 0.9091],
        [ 1.0101],
        [ 1.1111],
        [ 1.2121],
        [ 1.3131],
        [ 1.4141],
        [ 1.5152],
        [ 1.6162],
        [ 1.7172],
        [ 1.8182],
        [ 1.9192],
        [ 2.0202],
        [ 2.1212],
        [ 2.2222],
        [ 2.3232],
        [ 2.4242],
        [ 2.5253],
        [ 2.6263],
        [ 2.7273],
        [ 2.8283],
        [ 2.9293],
        [ 3.0303],
        [ 3.1313],
        [ 3.2323],
        [ 3.3333],
        [ 3.4343],
        [ 3.5354],
        [ 3.6364],
        [ 3.7374],
        [ 3.8384],
        [ 3.9394],
        [ 4.0404],
        [ 4.1414],
        [ 4.2424],
        [ 4.3434],
        [ 4.4444],
        [ 4.5455],
        [ 4.6465],
        [ 4.7475],
        [ 4.8485],
        [ 4.9495],
        [ 5.0505],
        [ 5.1515],
        [ 5.

In [20]:
# 데이터셋 클래스
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset


class MyDataset(Dataset):
    # Dataset 상속 시 len, getitem 필수 작성
    def __init__(self, X, y):
        super().__init__()
        self.X = X
        self.y = y
    def __len__(self):
        """전체 데이터 수를 반환"""
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

dataset = MyDataset(X, y)

model = nn.Linear(1, 1)
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)


In [24]:
# 2. Mini-batch
from torch.utils.data import DataLoader
                                    # 얘만 바꿔주면 됨 샘플이 100개 있는데 16개씩 자르다가 마지막에 4개가 남으면

# drop_last=True: 마지막 배치개수가 지정한 batchsize보다 작은 경우 버림
dataloader = DataLoader(dataset, batch_size=16, shuffle=True, drop_last=True)
model = nn.Linear(1, 1)
optimizer = optim.Adam(model.parameters(), lr=0.01) # 100/16만큼 반복

for epoch in range(200):
    for X_batch, y_batch in dataloader:
        # print(X_batch, y_batch)
        optimizer.zero_grad()
        pred = model(X_batch)
        loss = criterion(pred, y_batch)
        loss.backward()
        optimizer.step() # 표지판 생겼으니까 다시 갱신해준다.
    print(f'Epoch {epoch + 1} : Loss {loss.item():4f}')



Epoch 1 : Loss 486.494598
Epoch 2 : Loss 505.280243
Epoch 3 : Loss 337.825134
Epoch 4 : Loss 362.539948
Epoch 5 : Loss 296.844910
Epoch 6 : Loss 369.292542
Epoch 7 : Loss 512.157837
Epoch 8 : Loss 374.078613
Epoch 9 : Loss 258.254822
Epoch 10 : Loss 359.243622
Epoch 11 : Loss 296.633606
Epoch 12 : Loss 344.202026
Epoch 13 : Loss 252.457703
Epoch 14 : Loss 183.635971
Epoch 15 : Loss 243.293030
Epoch 16 : Loss 124.046165
Epoch 17 : Loss 193.938889
Epoch 18 : Loss 201.147827
Epoch 19 : Loss 235.166046
Epoch 20 : Loss 175.520493
Epoch 21 : Loss 206.577866
Epoch 22 : Loss 104.866234
Epoch 23 : Loss 164.114670
Epoch 24 : Loss 176.874802
Epoch 25 : Loss 126.013710
Epoch 26 : Loss 148.848206
Epoch 27 : Loss 110.960793
Epoch 28 : Loss 99.393761
Epoch 29 : Loss 153.774261
Epoch 30 : Loss 90.413216
Epoch 31 : Loss 95.180008
Epoch 32 : Loss 63.166660
Epoch 33 : Loss 121.852951
Epoch 34 : Loss 81.237976
Epoch 35 : Loss 94.963577
Epoch 36 : Loss 96.101837
Epoch 37 : Loss 62.506386
Epoch 38 : Loss 71

In [26]:
# 3. SGD
from torch.utils.data import DataLoader

dataloader = DataLoader(dataset, batch_size=1, shuffle=True)# 좀더 편하게 테스트 해볼 수 있다.
model = nn.Linear(1, 1)
optimizer = optim.Adam(model.parameters(), lr=0.01)

for epoch in range(200): # 1번 반복에 100번 업데이트
    for X_batch, y_batch in dataloader:
        # print(X_batch, y_batch)
        optimizer.zero_grad()
        pred = model(X_batch)
        loss = criterion(pred, y_batch)
        loss.backward()
        optimizer.step() # 표지판 생겼으니까 다시 갱신해준다.
    print(f'Epoch {epoch + 1} : Loss {loss.item():4f}')



Epoch 1 : Loss 79.825287
Epoch 2 : Loss 0.629116
Epoch 3 : Loss 61.782608
Epoch 4 : Loss 15.767574
Epoch 5 : Loss 11.020916
Epoch 6 : Loss 1.091463
Epoch 7 : Loss 3.162471
Epoch 8 : Loss 0.044209
Epoch 9 : Loss 0.273064
Epoch 10 : Loss 2.341588
Epoch 11 : Loss 3.358421
Epoch 12 : Loss 2.878263
Epoch 13 : Loss 0.474533
Epoch 14 : Loss 0.433272
Epoch 15 : Loss 0.002103
Epoch 16 : Loss 0.252925
Epoch 17 : Loss 0.428223
Epoch 18 : Loss 0.323838
Epoch 19 : Loss 0.321516
Epoch 20 : Loss 0.005441
Epoch 21 : Loss 0.139419
Epoch 22 : Loss 0.151458
Epoch 23 : Loss 0.004292
Epoch 24 : Loss 0.452677
Epoch 25 : Loss 1.588639
Epoch 26 : Loss 0.000884
Epoch 27 : Loss 0.200062
Epoch 28 : Loss 0.025479
Epoch 29 : Loss 0.049954
Epoch 30 : Loss 0.013153
Epoch 31 : Loss 0.580253
Epoch 32 : Loss 0.077571
Epoch 33 : Loss 0.219185
Epoch 34 : Loss 0.196713
Epoch 35 : Loss 0.314087
Epoch 36 : Loss 0.415514
Epoch 37 : Loss 0.012131
Epoch 38 : Loss 0.000245
Epoch 39 : Loss 0.026261
Epoch 40 : Loss 0.092795
Epoch